export class Datas {
	 clients=[
		{
			"id":"1",
			"firstname":"Mohamed",
			"lastname":"Amara",
			"gender":"male",
			"email":"mohamed@gmail.com",
			"phone":"22541478",
			"password":"mohamedamara",
			"adress":"ibn khouldoun",
			"city":"Tunis",
			"country":"Tunisie",
			"zip":"3260",
			"photo":"assets/dashboardClient/images/iiii.jpg",
			"cardNumber":"2154236521458563",
			"expiration":"12-12-2024",
			"cardCode":"08521453",
			"cardType":"MasterCard",
		},
		{
			"id":"2",
			"firstname":"Khira",
			"lastname":"Amara",
			"gender":"female",
			"email":"khira@gmail.com",
			"phone":"96521478",
			"password":"khiraamara",
			"adress":"Oesres",
			"city":"Lisbonne",
			"country":"Portugal",
			"zip":"32510",
			"photo":"assets/dashboardClient/images/2.jpg",
			"cardNumber":"2356147889560125",
			"expiration":"19-11-2025",
			"cardCode":"01452369",
			"cardType":"VisaCard",
		},
		{
			"id":"3",
			"firstname":"Ayoub",
			"lastname":"Amara",
			"gender":"male",
			"email":"ayoub@gmail.com",
			"phone":"27413658",
			"password":"ayoubamara",
			"adress":"Om somaa souk lahad",
			"city":"Kebili",
			"country":"Tunisie",
			"zip":"4230",
			"photo":"assets/dashboardClient/images/3.jpg",
			"cardNumber":"0214125863202147",
			"expiration":"12-10-2026",
			"cardCode":"03251459",
			"cardType":"MasterCard",
		},
		{
			"id":"4",
			"firstname":"Ilyess",
			"lastname":"Amara",
			"gender":"male",
			"email":"ilyessamara@gmail.com",
			"phone":"92081406",
			"password":"ilyessamara",
			"adress":"Souk Lahad",
			"city":"Kebili",
			"country":"Tunisie",
			"zip":"4212",
			"photo":"assets/dashboardClient/images/4.jpg",
			"cardNumber":"025412369852147",
			"expiration":"20-09-2022",
			"cardCode":"02581478",
			"cardType":"VisaCard",
		},
		{
			"id":"5",
			"firstname":"Dhaw",
			"lastname":"Gammar",
			"gender":"male",
			"email":"dhaw@gmail.com",
			"phone":"25428298",
			"password":"dhawgammar",
			"adress":"Bardo",
			"city":"Tunis",
			"country":"Tunisie",
			"zip":"3687",
			"photo":"assets/dashboardClient/images/5.jpg",
			"cardNumber":"3625410258963214",
			"expiration":"01-02-2021",
			"cardCode":"09658741",
			"cardType":"MasterCard",
		}
	];
	 entreprises=[

		{
			"id":"1",
			"name":"Digital Lab",
			"legal_forme":"SARL",
			"capital":"3000",
			"activity":"Marketing solutions",
			"adress":"Manzah 5",
			"city":"Tunis",
			"coutry":"Tunisie",
			"zip":"3000",
			"manager":"Dhaw Gammar",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"01-09-2020",
			"offer":"domipack",
			"ownerId":"5"
		},
		{
			"id":"2",
			"name":"Excellence",
			"legal_forme":"SARL",
			"capital":"6000",
			"activity":"Enseignement en ligne",
			"adress":"La Marsa",
			"city":"Tunis",
			"coutry":"Tunisia",
			"zip":"3100",
			"manager":"Mohamed Amara",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"20-10-2019",
			"offer":"scanpack",
			"ownerId":"1"
		},
		{
			"id":"3",
			"name":"Vivo Bio Tech",
			"legal_forme":"SA",
			"capital":"120000",
			"activity":"Technologies Biologies",
			"adress":"Porto",
			"city":"Lisbonne",
			"coutry":"Portugal",
			"zip":"7500",
			"manager":"Khira Amara",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"01-014-2018",
			"offer":"scanpack",
			"ownerId":"2"
		},
		{
			"id":"4",
			"name":"HighTech",
			"legal_forme":"SARL",
			"capital":"12000",
			"activity":"Software engineering",
			"adress":"Om somaa",
			"city":"Souk Lahad",
			"coutry":"Kebili",
			"zip":"4212",
			"manager":"Ilyess Amara",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"06-05-2017",
			"offer":"domisimple",
			"ownerId":"4"
		},
		{
			"id":"5",
			"name":"ProTech",
			"legal_forme":"SARL",
			"capital":"25000",
			"activity":"Embedded systems",
			"adress":"Rue 24,TSHCN",
			"city":"Berlin",
			"coutry":"Allemagne",
			"zip":"6321",
			"manager":"Ayoub Amara",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"01-01-2020",
			"offer":"scanpack",
			"ownerId":"3"
		},
		{
			"id":"6",
			"name":"Sahara Solar",
			"legal_forme":"SARL",
			"capital":"57000",
			"activity":"Solar energy",
			"adress":"Souk Lahad",
			"city":"kebili",
			"coutry":"Tunisie",
			"zip":"4230",
			"manager":"Mohamed Amara",
			"logo":"assets/dashboardClient/images/avatar.png",
			"registerDate":"20-03-2016",
			"offer":"domisimple",
			"ownerId":"1"
		}

	];
	 payment=[

		{
			"cardNumber":"2154236521458563",
			"expiration":"12-12-2024",
			"cardCode":"08521453",
			"cardType":"MasterCard",
			"ownerId":"1",
			

		},
		{
			"cardNumber":"2356147889560125",
			"expiration":"19-11-2025",
			"cardCode":"01452369",
			"cardType":"VisaCard",
			"ownerId":"2",


		},
		{
			"cardNumber":"0214125863202147",
			"expiration":"12-10-2026",
			"cardCode":"03251459",
			"cardType":"MasterCard",
			"ownerId":"3",

		},
		{
			"cardNumber":"025412369852147",
			"expiration":"20-09-2022",
			"cardCode":"02581478",
			"cardType":"VisaCard",
			"ownerId":"4",

		},
		{
			"cardNumber":"3625410258963214",
			"expiration":"01-02-2021",
			"cardCode":"09658741",
			"cardType":"MasterCard",
			"ownerId":"5",

		},
	];
	 letters=[

		{
			"id":"1",
			"seen":"yes",
			"state":"recovred",
			"date":"19-10-2020",
			"time":"20:35",
			"path":"assets/dashboardClient/images/bg-title-01.jpg",
			"EntrepriseId":"1",

		},
		{
			"id":"2",
			"seen":"yes",
			"state":"delivred",
			"date":"11-12-2020",
			"time":"08:14",
			"path":"assets/dashboardClient/images/bg-title-02.jpg",
			"EntrepriseId":"1",

		},
		{
			"id":"3",
			"seen":"no",
			"state":"delivred",
			"date":"01-12-2020",
			"time":"10:35",
			"path":"assets/dashboardClient/images/bg-title-02.jpg",
			"EntrepriseId":"1",

		},
		{
			"id":"4",
			"seen":"no",
			"state":"delivred",
			"date":"29-11-2020",
			"time":"12:45",
			"path":"assets/dashboardClient/images/bg-title-02.jpg",
			"EntrepriseId":"2",

		},
		{
			"id":"5",
			"seen":"no",
			"state":"delivred",
			"date":"05-12-2020",
			"time":"16:30",
			"path":"assets/dashboardClient/images/bg-title-01.jpg",
			"EntrepriseId":"3",

		},
		{
			"id":"6",
			"seen":"no",
			"state":"ready",
			"date":"02-12-2020",
			"time":"09:05",
			"path":"assets/dashboardClient/images/bg-title-01.jpg",
			"EntrepriseId":"4",

		},
		{
			"id":"7",
			"seen":"yes",
			"state":"recovered",
			"date":"03-12-2020",
			"time":"15:18",
			"path":"assets/dashboardClient/images/bg-title-02.jpg",
			"EntrepriseId":"5",

		},
		{
			"id":"8",
			"seen":"yes",
			"state":"ready",
			"date":"25-11-2020",
			"time":"13:58",
			"path":"assets/dashboardClient/images/bg-title-02.jpg",
			"EntrepriseId":"6",

		},
		{
			"id":"9",
			"seen":"no",
			"state":"delivred",
			"date":"04-12-2020",
			"time":"19:52",
			"path":"assets/dashboardClient/images/bg-title-01.jpg",
			"EntrepriseId":"3",

		},
		{
			"id":"10",
			"seen":"yes",
			"state":"recovred",
			"date":"10-10-2020",
			"time":"19:52",
			"path":"assets/dashboardClient/images/bg-title-01.jpg",
			"EntrepriseId":"4",

		},
	];
	constructor(){

	}
}
